### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by eikibw** [gutris1/sd-hub#5]
I can't use it, it loading all the time. 
![Screenshot 2024-05-11 174510](https://github.com/gutris1/sd-hub/assets/117745256/0a16638d-2402-4e58-bd7b-259721729daa)

**Comment by gutris1** [comment]
> I can't use it, it loading all the time. ![Screenshot 2024-05-11 174510](https://private-user-images.githubusercontent.com/117745256/329775403-0a16638d-2402-4e58-bd7b-259721729daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDU0MTcsIm5iZiI6MTcxNTQ0NTExNywicGF0aCI6Ii8xMTc3NDUyNTYvMzI5Nzc1NDAzLTBhMTY2MzhkLTI0MDItNGU1OC1iZDdiLTI1OTcyMTcyOWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNjMxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTEwZmE2MGQxMzJlMmY0OGM0MGY2ZWY1ZWQ0ZWEzYjJmODdlNGU5MjVlMWYxOWI1N2JkMzg3NGNkMmQ2YjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZDAz6hTooOMAgVDdxTYaSlgH1aCvezFCGV_DKeya0dQ)

that's because of connection
press F5 or something.

**Comment by eikibw** [comment]
> that's because of connection press F5 or something.

Did that. F5, restart ui, everything. It's still infinite loading.

**Comment by gutris1** [comment]
> > that's because of connection press F5 or something.
> 
> Did that. F5, restart ui, everything. It's still infinite loading.

I can't do anything about it, that is simply a connection issue

**Comment by eikibw** [comment]
Fortunately, I can use the input box. I just tested it, I can download from drive. it's just the HG token and civitai API box that keep on loading.

**Comment by gutris1** [comment]
> Fortunately, I can use the input box. I just tested it, I can download from drive. it's just the HG token and civitai API box that keep on loading.

I think I've fixed it. you can try the new version
